# Generated by Django 5.0.1 on 2024-02-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agrosystems", "0004_alter_project_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytask",
            name="status",
            field=models.CharField(default="Not complete", max_length=20),
        ),
    ]
